# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Licence 1', url: '_posts/l1'}
- {name: 'Licence 2', url: 'l2'}
- {name: 'Licence 3', url: 'l3'}
- {name: 'Photos étranger', url: 'photo'}
- {name: 'Blagues', url: 'blagues'}
- {name: 'Contact', url: 'contact'}

# Customize site text
pagination:
  next_page: 'Récent'
  previous_page: 'Moins récent'

post_date_prefix: 'Rajouté le'
